cache: bundler

language: ruby

rvm:
  - 2.2.9
  - 2.3.5
  - 2.4.4
  - 2.5.1

sudo: false

branches:
  only: master

before_install:
  - gem update --system
  - gem install bundler

env:
  global:
    - ZUORA_CLIENT_ID=something
    - ZUORA_CLIENT_SECRET=secret
    - ZUORA_DOMAIN=rest.apisandbox.zuora.com
